import type { MembershipRequest, Profile } from '@workspace/api-client-react';

export const demoProfiles: Profile[] = [
  {
    id: 'lea-m',
    name: 'Léa Martin',
    initials: 'LM',
    age: 17,
    neighborhood: 'Les Tilleuls',
    avatarUrl: null,
    bio: 'Je collectionne les idées et les transforme en petits projets utiles.',
    activities: ['Photo', 'Couture', 'Musique'],
    project: 'Un fanzine du village, fait à plusieurs mains.',
    contact: 'lea.martin@village.test',
    instagram: '@lea.en.images',
    privacy: 'community',
    status: 'approved',
  },
  {
    id: 'yanis-b',
    name: 'Yanis Benali',
    initials: 'YB',
    age: 19,
    neighborhood: 'Le Verger',
    avatarUrl: null,
    bio: 'Toujours partant pour un match, une balade ou comprendre comment les choses fonctionnent.',
    activities: ['Basket', 'Réparation', 'Cuisine'],
    project: 'Réparer les vélos oubliés au fond des garages.',
    contact: null,
    instagram: '@yanis.fait',
    privacy: 'community',
    status: 'approved',
  },
  {
    id: 'ines-r',
    name: 'Inès Roux',
    initials: 'IR',
    age: 16,
    neighborhood: 'La Place',
    avatarUrl: null,
    bio: 'Je dessine les gens quand ils ne regardent pas et je connais les meilleurs coins calmes.',
    activities: ['Illustration', 'Lecture', 'Nature'],
    project: 'Une carte dessinée des petits chemins autour du village.',
    contact: null,
    instagram: null,
    privacy: 'community',
    status: 'approved',
  },
  {
    id: 'noe-p',
    name: 'Noé Petit',
    initials: 'NP',
    age: 21,
    neighborhood: 'Les Vignes',
    avatarUrl: null,
    bio: 'Je fabrique, je plante, puis je recommence avec quelqu’un.',
    activities: ['Jardin', 'Bois', 'Musique'],
    project: 'La serre partagée derrière la salle des fêtes.',
    contact: 'noe.petit@village.test',
    instagram: null,
    privacy: 'private',
    status: 'approved',
  },
  {
    id: 'zoe-c',
    name: 'Zoé Charlier',
    initials: 'ZC',
    age: 18,
    neighborhood: 'Le Verger',
    avatarUrl: null,
    bio: 'Un appareil argentique dans le sac, toujours.',
    activities: ['Photo', 'Cinéma', 'Cuisine'],
    project: null,
    contact: null,
    instagram: '@zoe.ch',
    privacy: 'community',
    status: 'approved',
  },
  {
    id: 'samir-d',
    name: 'Samir Diallo',
    initials: 'SD',
    age: 20,
    neighborhood: 'Les Tilleuls',
    avatarUrl: null,
    bio: 'Je passe d’un beat à l’autre et j’aime les discussions qui durent.',
    activities: ['Musique', 'Basket', 'Cuisine'],
    project: 'Une scène ouverte un vendredi par mois.',
    contact: null,
    instagram: '@samir.sons',
    privacy: 'community',
    status: 'approved',
  },
];

export const demoRequests: MembershipRequest[] = [
  {
    id: 'request-ana',
    name: 'Anaïs Giraud',
    email: 'anais.giraud@example.com',
    neighborhood: 'La Place',
    submittedAt: '2025-02-18T10:24:00.000Z',
    status: 'pending',
  },
  {
    id: 'request-louis',
    name: 'Louis Rey',
    email: 'louis.rey@example.com',
    neighborhood: 'Les Vignes',
    submittedAt: '2025-02-17T16:40:00.000Z',
    status: 'pending',
  },
  {
    id: 'request-maya',
    name: 'Maya Colin',
    email: 'maya.colin@example.com',
    neighborhood: 'Le Verger',
    submittedAt: '2025-02-16T09:15:00.000Z',
    status: 'pending',
  },
];
