import type { Profile } from "@workspace/api-client-react";

export const demoProfiles: Profile[] = [
  ["grovogui-pokpa-zeze", "Pokpa zézé Grovogui", "PG", "Liberia", "Salarié"],
  ["bea-ibrahim-sefouou", "Ibrahim Sefouou Béa", "IB", "Labé", "Étudiant"],
  ["koivogui-emile", "Emile Koivogui", "EK", "Kindia", "Étudiant"],
  ["beavogui-joseph-zeze", "Joseph zeze Beavogui", "JB", "Mamou", "Salarié"],
  [
    "koivogui-barre-moise",
    "Barre Moise koivogui",
    "BK",
    "Beyla",
    "En recherche d’emploi",
  ],
  ["beavogui-foromo", "Foromo Béavogui", "FB", "Beyla", "Élève/Lycéen"],
  [
    "kalivogui-kaba",
    "Kaba Kalivogui",
    "KK",
    "Conakry",
    "En recherche d’emploi",
  ],
  ["koivogui-sema-gouo", "Sèma gouo Koïvogui", "SK", "Kankan", "Étudiant"],
  ["kalivogui-nette", "Nette Kalivogui", "NK", "Conakry", "Étudiant"],
  ["koivogui-daniel-koly", "Daniel Koly KOIVOGUI", "DK", "Kindia", "Salarié"],
  ["koivogui-eddy", "Eddy Koivogui", "EK", "Macenta", "Autre"],
  ["kalivogui-barre", "Barre Kalivogui", "BK", "Dubreka", "Autre"],
  ["koivogui-peve", "Pévé KOÏVOGUI", "PK", "Conakry", "Autre"],
  ["kalivogui-jacques", "Jacques Kalivogui", "JK", "Mamou", "Salarié"],
  [
    "koivogui-justin-kekoura",
    "Justin kékoura Koïvogui",
    "JK",
    "Conakry",
    "Autre",
  ],
  [
    "koivogui-simon-pierre",
    "Simon pierre Koivogui",
    "SK",
    "Conakry",
    "Salarié",
  ],
  ["koivogui-bernard", "Bernard Koïvogui", "BK", "Kindia", "Étudiant"],
  ["koivogui-barres", "Barrès Koïvogui", "BK", "Kindia", "Étudiant"],
  ["guilavogui-barre", "Barrè Guilavogui", "BG", "Mamou", "Agriculteur"],
  ["beavogui-gbade", "GBADE BEAVOGUI", "GB", "Conakry", "Salarié"],
  ["beavogui-barre-france", "Barre BEAVOGUI", "BB", "France", "Étudiant"],
].map(([id, name, initials, neighborhood, profession]) => ({
  id,
  name,
  initials,
  neighborhood,
  avatarUrl: null,
  bio: `Profession ou statut : ${profession}.`,
  activities: [profession],
  project: null,
  contact: null,
  instagram: null,
  privacy: "private",
  status: "approved",
})) as Profile[];
